services:
  postgres:
    image: postgres:15
    container_name: postgres-container
    ports:
      - "5432:5432"  
    environment:
      POSTGRES_USER: postgres        
      POSTGRES_PASSWORD: mypassword 
      POSTGRES_DB: postgres       
    volumes:
      - postgres-data:/var/lib/postgresql/data" 

  cassandra:
    image: cassandra:4.0.4
    container_name: cassandra-container
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=admin
    volumes:
      - cassandra-data:/var/lib/cassandra

volumes:
  postgres-data:
  cassandra-data:

